
CREATE TABLE DocumentType (
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR(50) NOT NULL,
Descpt NVARCHAR(100)
);
GO

CREATE TABLE Country (
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR(100) NOT NULL,
CountryCode NVARCHAR(5) NOT NULL
);
GO

CREATE TABLE Province(
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(100) NOT NULL,
CountryId INT FOREIGN KEY REFERENCES Country(Id)
);
GO

CREATE TABLE City (
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(100),
CityId INT FOREIGN KEY REFERENCES Province(Id)
);
GO

CREATE TABLE Distrit (
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(100) NOT NULL,
CityId INT FOREIGN KEY REFERENCES City(Id)
);
GO

CREATE TABLE Employee ( 
Id INT PRIMARY KEY IDENTITY(1,1),
DocumentTypeId INT FOREIGN KEY REFERENCES DocumentType(Id),
DocumentId NVARCHAR(50) NOT NULL,
Name NVARCHAR(100) NOT NULL,
LastName NVARCHAR(100) NOT NULL,
BirthDay DATETIME NOT NULL,
Email NVARCHAR(100) NOT NULL,
JoinedDate DATETIME NOT NULL DEFAULT GETDATE(),
CostPerHour DECIMAL NOT NULL,
IBAN NVARCHAR(50),
CountryId INT FOREIGN KEY REFERENCES Country(Id),
StreetAddres NVARCHAR(200),
PhoneNumber NVARCHAR,
ProfilePhoto NVARCHAR(255)
);
GO